### ISSUE TITLE
Integrating changes back into NVIDIA/DIGITS

### ISSUE THREAD

**Issue by lukeyeager** [batra-mlp-lab/DIGITS#4]
Hi guys, great discussion this morning!

I'd like to get a clear picture of (1) what you've done and (2) how feasible it would be to integrate each of those things back upstream. Here's what I've got so far:
### Add support for workspaces

Is each DIGITS instance owned by a single user? Or is each DIGITS instance partitioned into multiple workspaces? Can a Job be owned by multiple users or by a group of users?

Why did you switch to Django? Did you replace Flask entirely? How much work was it?
### Interface with  Cloud storage

How did you handle authentication? Do you download the images locally or just read them directly from a URL?

When saving things back to the cloud, did you save an entire job directory or just specific files? Did you save the `status.pickle` files?
### Add pretrained model as a new ModelJob

We're discussing doing a re-architecture which would make this easier. The ModelZoo download is an especially cool feature that we'd like to have in DIGITS.
### Store activations to disk

Did you save the weights, too? Did you save the whole activations even for fully connected layers? How big do those files get?

_Sorry this is an absurd number of questions. I guess we could break the discussion into separate threads if that's helpful? Pointers to specific commits with clear commit messages for each of these features would be much appreciated._

**Comment by ahmedosman** [comment]
Hi Luke,

Re- Add support for workspaces: 
1- A single Digits instances is shared across all workspace. Hence, all the jobs are running on a single DIGITS server. 
2- Each workspace has an ID, that is passed as a query parameter in the URL to DIGITS. Whenever a job is created within a workspace it gets a unique ID that represents the workspace it was created in and basically we filter out the jobs by the workspace id to load jobs relevant to the specific workspace of interest.
3- We still use Flask and didn't migrate to Django. Just for workspace management we used Django Organisations, which handles the user management at the backend (adding/removing/inviting users). We intentionally didn't carry substantial changes in the DIGITS code architecture in order to avoid conflicts when merging and pulling from the main DIGITS branch.

Re- Interface with Cloud storage (Still in Progress).
For authentication, we didn't demo it this morning. A CloudCV user as prior step to using cloud storage authenticates his cloud storage accounts before using them. For google drive and dropbox they have social authentication api that we've used. For S3 authentication, we used a python tool called boto (https://github.com/boto/boto). The cloud storage API has not been integrated with DIGITS yet. 

Re-Store activations to disk: By default we only export the last class probability layer. However user can specify layer names as a comma separated list  (i.e pool1,fc7,fc8 ) and we'll export them as a single matlab .mat file or .npy file, the more layers you request the bigger the file will be.

I suggest we have a meeting/s scheduled after the end of August to discuss technically the changes we made in DIGITS codebase - a handover meeting?
